// mod print;
// mod var;
// mod types;
// mod strings;
// mod tuples;
// mod arrays;
// mod vectors;
// mod conditionals;
// mod loops;
// mod functions;
// mod pointer;
// mod structs;
// mod enums;
mod cli;
fn main() {
    // print::run();
    // var::run();
    // types::run();
    // strings::run();
    // tuples::run();
    // arrays::run();
    // vectors::run();
    // conditionals::run();
    // loops::run();
    // functions::run();
    // pointer::run();
    // structs::run();
    // enums::run();
    cli::run();
}
